
CREATE TABLE Customer(
CustomerID INT PRIMARY KEY,
FName VARCHAR(20),
LName VARCHAR(20),
Gender CHAR(1),
[Address] VARCHAR(40),
PhoneNo VARCHAR(15),
EmailAddress VARCHAR(50)
);

CREATE TABLE Supplier(
SupplierID INT PRIMARY KEY,
CoName VARCHAR(40),
PhysicalAddress VARCHAR(40),
PostalAddress VARCHAR(40)
);

CREATE TABLE DVD(
DVDID INT PRIMARY KEY,
Genre VARCHAR (20),
Rating INT,
Director VARCHAR(40),
ReleaseDate DATE,
MainActor1 VARCHAR(30),
MainActor2 VARCHAR(30),
QtyInStock INT NOT NULL,
SalePrice MONEY,
RentalPrice MONEY
);

CREATE TABLE PurchaseOrder(
POID INT PRIMARY KEY,
SupplierID INT FOREIGN KEY (SupplierID) REFERENCES Supplier ON DELETE SET NULL
);

CREATE TABLE PurchaseOrderLine(
POLID INT PRIMARY KEY,
DVDID INT FOREIGN KEY (DVDID) REFERENCES DVD ON DELETE SET NULL,
[Name] VARCHAR(40),
Quantity INT,
Cost MONEY,
POID INT FOREIGN KEY (POID) REFERENCES PurchaseOrder ON DELETE SET NULL
);

CREATE TABLE RentalLine(
RLID INT PRIMARY KEY,
DVDID INT FOREIGN KEY (DVDID) REFERENCES DVD ON DELETE SET NULL
);

CREATE TABLE Rental(
RentalID INT PRIMARY KEY,
RentalDate DATE NOT NULL,
ReturnDate DATE NOT NULL,
RLID INT FOREIGN KEY (RLID) REFERENCES RentalLine ON DELETE SET NULL,
CustomerID INT FOREIGN KEY (CustomerID) REFERENCES Customer ON DELETE CASCADE
);

SELECT * FROM Customer,Supplier,DVD,PurchaseOrder,PurchaseOrderLine,RentalLine,Rental;

DROP TABLE Rental;
DROP TABLE RentalLine;
DROP TABLE PurchaseOrderLine;
DROP TABLE PurchaseOrder;
DROP TABLE Customer;
DROP TABLE Supplier;
DROP TABLE DVD;
